### ISSUE TITLE
Support traceparent propagation headers

### ISSUE THREAD

**Issue by towolf** [fortio/fortiotel#190]
The defaulting of `-b3multi` causes the condition that transmits traceparent w3c headers to not be reachable:

https://github.com/fortio/fortiotel/blob/main/fortio_with_otel.go#L49

https://github.com/fortio/fortiotel/blob/cae044e981c7f9dbcde330a7e0115a1c3526cecb/fortio_with_otel.go#L67-L72

**Comment by ldemailly** [comment]
Yes so you should invoke fortiotel with `-b3multi=false` (or put that in the configmap/config flag dir) ?

**Comment by towolf** [comment]
Ah yes, didn't realize that works.

**Comment by ldemailly** [comment]
yeah, no problem, go flags syntax to undo a `true` default isn't always intuitive
